#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/config/config.ini

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="/tmp/$0.$$.$RANDOM"
  cat <<EOF >"$TMP_FILE"
[analytics]
enabled = False
EOF

  install -dm755 -o $PUID -g $PGID "$(dirname "$CONFIG_FILE")"
  install -m644  -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
else
  # disable analytics
  sed -i -r "/^\[analytics\]$/,/^\[.*/{ /^enabled[ ]*=/s/=.*/= False/ }" "$CONFIG_FILE"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID python3 /app/bazarr.py --no-update --config=/config
